apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: first-app
  namespace: argocd-june

spec:
  project: myproj

  # Source of the application manifests
  source:
    repoURL: https://github.com/tamilarasan4/argoproj.git
    targetRevision: HEAD
    path: first-app

    # helm specific config
    helm:
      # Release name override (defaults to application name)
      releaseName: first-app

      # Helm values files for overriding values in the helm chart
      # The path is relative to the spec.source.path directory defined above
      #valueFiles:
      #  - values-test.yaml

    
  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc # Replace me with propper host
    namespace: myproj-first-app

  # Sync policy
  syncPolicy:
    automated:
      prune: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
      - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')
      
  # Ignore differences at the specified json pointers
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas


